=== WebOfTrust/vLEI/schema/acdc/qualified-vLEI-issuer-vLEI-credential.json
{
  "$id": "Enbs9f3VtP6w_X2LOXax26FaW93Sp3Imv0hUdUk8E9HU",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Qualified vLEI Issuer Credential",
  "description": "A vLEI Credential issued by GLEIF to Qualified vLEI Issuers which allows the Qualified vLEI Issuers to issue, verify and revoke Legal Entity vLEI Credentials and Legal Entity Official Organizational Role vLEI Credentials",
  "credentialType": "QualifiedvLEIIssuervLEICredential",
  "properties": {
    "v": {
      "type": "string"
    },
    "d": {
      "type": "string"
    },
    "u": {
      "description": "one time use nonce",
      "type": "string"
    },
    "i": {
      "type": "string"
    },
    "ri": {
      "description": "credential status registry",
      "type": "string"
    },
    "s": {
      "description": "schema SAID",
      "type": "string"
    },
    "a": {
      "oneOf": [
        {
          "description": "attribute block SAID",
          "type": "string"
        },
        {
          "description": "attribute block",
          "properties": {
            "d": {
              "type": "string"
            },
            "i": {
              "type": "string"
            },
            "dt": {
              "description": "issuance date time",
              "format": "date-time",
              "type": "string"
            },
            "LEI": {
              "type": "string"
            },
            "gracePeriod": {
              "default": 90,
              "type": "integer"
            }
          },
          "additionalProperties": false,
          "required": [
            "i",
            "dt",
            "LEI"
          ],
          "type": "object"
        }
      ]
    },
    "r": {
      "oneOf": [
        {
          "description": "rules block SAID",
          "type": "string"
        },
        {
          "description": "rules block",
          "type": "object",
          "properties": {
            "d": {
              "type": "string",
              "description": "SAID of rules block"
            },
            "usageDisclaimer": {
              "type": "object",
              "description": "Usage Disclaimer",
              "properties": {
                "l": {
                  "description": "associated legal language",
                  "const": "Usage of a valid Legal Entity vLEI Credential does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws."
                }
              }
            },
            "issuanceDisclaimer": {
              "type": "object",
              "description": "Issuance Disclaimer",
              "properties": {
                "l": {
                  "description": "associated legal language",
                  "const": "Issuance of a valid Legal Entity vLEI Credential only establishes that the information in the requirements in the Identity Verification section 6.3 of the Credential Governance Framework were met in accordance with the vLEI Ecosystem Governance Framework."
                }
              }
            }
          },
          "additionalProperties": false,
          "required": [
            "d",
            "usageDisclaimer",
            "issuanceDisclaimer"
          ]
        }
      ]
    },
    "e": {
      "oneOf": [
        {
          "description": "edge block SAID",
          "type": "string"
        },
        {"type": "object"}
      ]
    }
  },
  "additionalProperties": false,
  "required": [
    "i",
    "ri",
    "s",
    "d"
  ],
  "type": "object"
}

=== WebOfTrust/vLEI/samples/acdc/legal-entity-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EBdXt3gIXOf2BBWNHdSXCJnFJL5OuQPyM5K0neuniccM",
  "i": "did:keri:EmkPreYpZfFk66jpf3uFv7vklXKhzBrAqjsKAn2EDIPM",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "E46jrVPTzlSkUPqGGeIZ8a8FWS7a6s4reAXRZOkogZ2A",
  "a": {
    "d": "EgveY4-9XgOcLxUderzwLIr9Bf7V_NHwY1lkFrn9y2PY",
    "i": "did:keri:EQzFVaMasUf4cZZBKA0pUbRc9T8yUXRFLyM1JDASYqAA",
    "dt": "2021-06-09T17:35:54.169967+00:00",
    "LEI": "254900OPPU84GM83MG36"
  },
  "e": {
    "d": "EIl3MORH3dCdoFOLe71iheqcywJcnjtJtQIYPvAu6DZA",
    "qvi": {
      "n": "Et2DOOu4ivLsjpv89vgv6auPntSLx4CvOhGUxMhxPS24",
      "s": "EWCeT9zTxaZkaC_3-amV2JtG6oUxNA36sCC0P5MI7Buw"
    }
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid Legal Entity vLEI Credential does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws."
    },
    "issuanceDisclaimer": {
      "l": "Issuance of a valid Legal Entity vLEI Credential only establishes that the information in the requirements in the Identity Verification section 6.3 of the Credential Governance Framework were met in accordance with the vLEI Ecosystem Governance Framework."
    }
  }
}

=== WebOfTrust/vLEI/samples/acdc/v1.1.0/compact-qualified-vLEI-issuer-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EYo4R9I08Et5H5SWKG8ZMS83r8FmRtfahN0V9NbG9zdw",
  "i": "did:keri:Ei5csblWpTy22uVkbZrZxvSUORxPvIlrfpq2e1hKTtfA",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "ECcj1CBn4dpo6ZOmZQNtAjXxT4_MsVXipt5VTPjvSAf0",
  "a": "Ea4ny_YZAtAGUwGSyH7iFiKjpM3yFiDHcjrdomqt7Ryk",
  "e": {}
}

=== WebOfTrust/vLEI/samples/acdc/qualified-vLEI-issuer-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EYo4R9I08Et5H5SWKG8ZMS83r8FmRtfahN0V9NbG9zdw",
  "i": "did:keri:Ei5csblWpTy22uVkbZrZxvSUORxPvIlrfpq2e1hKTtfA",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "ECcj1CBn4dpo6ZOmZQNtAjXxT4_MsVXipt5VTPjvSAf0",
  "a": {
    "d": "Ea4ny_YZAtAGUwGSyH7iFiKjpM3yFiDHcjrdomqt7Ryk",
    "i": "did:keri:EP2ukuiw_0xcp943NWz4IRnNtxwx7rzROwV1D_ZRP0XQ",
    "dt": "2021-06-09T17:35:54.169967+00:00",
    "LEI": "5493001KJTIIGC8Y1R12"
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid Legal Entity vLEI Credential does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws."
    },
    "issuanceDisclaimer": {
      "l": "Issuance of a valid Legal Entity vLEI Credential only establishes that the information in the requirements in the Identity Verification section 6.3 of the Credential Governance Framework were met in accordance with the vLEI Ecosystem Governance Framework."
    }
  }
}
