=== WebOfTrust/vLEI/samples/oobis/.well-known/keri/oobi/EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy/index.json
{"$id":"EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy","$schema":"http://json-schema.org/draft-07/schema#","title":"Legal Entity Official Organizational Role vLEI Credential","description":"A vLEI Role Credential issued by a Qualified vLEI issuer to official representatives of a Legal Entity","type":"object","credentialType":"LegalEntityOfficialOrganizationalRolevLEICredential","version":"1.0.0","properties":{"v":{"description":"Version","type":"string"},"d":{"description":"Credential SAID","type":"string"},"u":{"description":"One time use nonce","type":"string"},"i":{"description":"QVI Issuer AID","type":"string"},"ri":{"description":"Credential status registry","type":"string"},"s":{"description":"Schema SAID","type":"string"},"a":{"oneOf":[{"description":"Attributes block SAID","type":"string"},{"$id":"ELDXjQ-FnKApK1DJhzmtKDcnfoJ9qusQr1Qz5g9MFt0o","description":"Attributes block","type":"object","properties":{"d":{"description":"Attributes block SAID","type":"string"},"i":{"description":"Person Issuee AID","type":"string"},"dt":{"description":"Issuance date time","type":"string","format":"date-time"},"LEI":{"description":"LEI of the Legal Entity","type":"string","format":"ISO 17442"},"personLegalName":{"description":"Recipient name as provided during identity assurance","type":"string"},"officialRole":{"description":"Official role title","type":"string"}},"additionalProperties":false,"required":["i","dt","LEI","personLegalName","officialRole"]}]},"e":{"oneOf":[{"description":"Edges block SAID","type":"string"},{"$id":"EMsSqaJsthSBA4OINZ1_fxfNVkgEPF-Sg5fq-vXM7Z6b","description":"Edges block","type":"object","properties":{"d":{"description":"Edges block SAID","type":"string"},"auth":{"description":"Chain to Auth vLEI credential from legal entity","type":"object","properties":{"n":{"description":"SAID of the ACDC to which the edge connects","type":"string"},"s":{"description":"SAID of required schema of the credential pointed to by this node","type":"string","const":"EKA57bKBKxr_kN7iN5i7lMUxpMG-s19dRcmov1iDxz-E"},"o":{"description":"Operator indicating this node is the issuer","type":"string","const":"I2I"}},"additionalProperties":false,"required":["n","s","o"]}},"additionalProperties":false,"required":["d","auth"]}]},"r":{"oneOf":[{"description":"Rules block SAID","type":"string"},{"$id":"ECllqarpkZrSIWCb97XlMpEZZH3q4kc--FQ9mbkFMb_5","description":"Rules block","type":"object","properties":{"d":{"description":"Rules block SAID","type":"string"},"usageDisclaimer":{"description":"Usage Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."}}},"issuanceDisclaimer":{"description":"Issuance Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."}}}},"additionalProperties":false,"required":["d","usageDisclaimer","issuanceDisclaimer"]}]}},"additionalProperties":false,"required":["i","ri","s","d","e","r"]}

=== WebOfTrust/vLEI/samples/acdc/v1.1.0/compact-legal-entity-official-organizational-role-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "E1qH1E2zo7rnW1Pwm3NuYOXZ1SsVH3yeV2Iifj2wtCgA",
  "i": "did:keri:EZBfSGG5k1CZYk1QH3GXFPtEwLHf0H06zuDUEJRyar1E",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "EDg-Ji3kmi_G97Jctxeajpmp1-A8gSpeyElm-XCzTxiE",
  "a": "ErmVM5JGLewHJrSqIuhwWktoIlfffh7sHIGAQvtcFSU",
  "e": "EBDmgKOAEwnMGsofWg2m0l63J1awfJafqJyCzTnVkdSw",
  "r": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU"
}

=== WebOfTrust/vLEI/samples/acdc/v1.1.0/compact-legal-entity-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EBdXt3gIXOf2BBWNHdSXCJnFJL5OuQPyM5K0neuniccM",
  "i": "did:keri:EmkPreYpZfFk66jpf3uFv7vklXKhzBrAqjsKAn2EDIPM",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "E46jrVPTzlSkUPqGGeIZ8a8FWS7a6s4reAXRZOkogZ2A",
  "a": "EgveY4-9XgOcLxUderzwLIr9Bf7V_NHwY1lkFrn9y2PY",
  "e": "EIl3MORH3dCdoFOLe71iheqcywJcnjtJtQIYPvAu6DZA",
  "r": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU"
}

=== WebOfTrust/vLEI/samples/acdc/v1.0.0/legal-entity-official-organizational-role-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "E1qH1E2zo7rnW1Pwm3NuYOXZ1SsVH3yeV2Iifj2wtCgA",
  "i": "did:keri:EZBfSGG5k1CZYk1QH3GXFPtEwLHf0H06zuDUEJRyar1E",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "EDg-Ji3kmi_G97Jctxeajpmp1-A8gSpeyElm-XCzTxiE",
  "a": {
    "d": "ErmVM5JGLewHJrSqIuhwWktoIlfffh7sHIGAQvtcFSU",
    "i": "did:keri:E70sYPRHygB9aOzgg_xEbI5RCVyRRCAXWG9uHyRNrqYE",
    "dt": "2021-06-09T17:35:54.169967+00:00",
    "LEI": "254900YH3ZCDPE1E5306",
    "personLegalName": "John Smith",
    "officialRole": "Chief Executive Officer"
  },
  "e": {
    "d": "EBDmgKOAEwnMGsofWg2m0l63J1awfJafqJyCzTnVkdSw",
    "auth": {
      "n": "Et2DOOu4ivLsjpv89vgv6auPntSLx4CvOhGUxMhxPS24",
      "s": "EKA57bKBKxr_kN7iN5i7lMUxpMG-s19dRcmov1iDxz-E",
      "o": "I2I"
    }
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."
    },
    "issuanceDisclaimer": {
      "l": "All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."
    }
  }
}

=== WebOfTrust/vLEI/samples/acdc/compact-oor-authorization-vlei-credential.json
{
  "v": "ACDC10JSON0004e4_",
  "d": "EuF1gpodKbbqS0fqmUiOYf-MusuNvi0OmY8Js6SKSdfE",
  "i": "EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws",
  "ri": "EuqwB_iOD86eK0ynAhA6AYwWvPeBhvmbcmOD-9cCmiVU",
  "s": "EDpuiVPt4_sa1pShx6vOCnseru1edVPeNvRaQm6HrmMI",
  "a": "E9-86Jag34CrJpfNFz_-7E5HA0Dj0FvcYNoFVe7qwkiI",
  "e": "EsOf5_YgX_64z4YuHNFWLUnIKcyvsVQOe_vJ_638X6gE",
  "r": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU"
}

=== WebOfTrust/vLEI/samples/acdc/compact-legal-entity-engagement-context-role-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EpcEvrX2gGTpmKbIG25GSA7_LsWwwzVQ6aUilgBubpGI",
  "u": "IY7-g7wTfta1087YAdUXTbuI0Vklqt8pQxTgc3Rtz0o",
  "i": "did:keri:EmSIYYxvgtKn9jAp8GcK3fXOwTeyBIcAnRnyrLNfKjVI",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "EZdaE1HCu2ZhyIhpXTWfGSLS2kirKexaC-4up3sIUz1I",
  "a": "EG7PfBZbyXS0huxbnvMD-jOdTnDCCaT4CO6xId-ATNWg",
  "e": "EBDmgKOAEwnMGsofWg2m0l63J1awfJafqJyCzTnVkdSw",
  "r": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU"
}
