=== WebOfTrust/vLEI/samples/oobis/.well-known/keri/oobi/ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY/index.json
{"$id":"ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY","$schema":"http://json-schema.org/draft-07/schema#","title":"Legal Entity vLEI Credential","description":"A vLEI Credential issued by a Qualified vLEI issuer to a Legal Entity","type":"object","credentialType":"LegalEntityvLEICredential","version":"1.0.0","properties":{"v":{"description":"Version","type":"string"},"d":{"description":"Credential SAID","type":"string"},"u":{"description":"One time use nonce","type":"string"},"i":{"description":"QVI Issuer AID","type":"string"},"ri":{"description":"Credential status registry","type":"string"},"s":{"description":"Schema SAID","type":"string"},"a":{"oneOf":[{"description":"Attributes block SAID","type":"string"},{"$id":"EJ6bFDLrv50bHmIDg-MSummpvYWsPa9CFygPUZyHoESj","description":"Attributes block","type":"object","properties":{"d":{"description":"Attributes block SAID","type":"string"},"i":{"description":"LE Issuer AID","type":"string"},"dt":{"description":"issuance date time","type":"string","format":"date-time"},"LEI":{"description":"LE Issuer AID","type":"string","format":"ISO 17442"}},"additionalProperties":false,"required":["i","dt","LEI"]}]},"e":{"oneOf":[{"description":"Edges block SAID","type":"string"},{"$id":"EDh9sp5cPk0-yo5sFMo6WJS1HMBYIOYCwJrnPvNaH1vI","description":"Edges block","type":"object","properties":{"d":{"description":"Edges block SAID","type":"string"},"qvi":{"description":"QVI node","type":"object","properties":{"n":{"description":"Issuer credential SAID","type":"string"},"s":{"description":"SAID of required schema of the credential pointed to by this node","type":"string","const":"EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao"}},"additionalProperties":false,"required":["n","s"]}},"additionalProperties":false,"required":["d","qvi"]}]},"r":{"oneOf":[{"description":"Rules block SAID","type":"string"},{"$id":"ECllqarpkZrSIWCb97XlMpEZZH3q4kc--FQ9mbkFMb_5","description":"Rules block","type":"object","properties":{"d":{"description":"Rules block SAID","type":"string"},"usageDisclaimer":{"description":"Usage Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."}}},"issuanceDisclaimer":{"description":"Issuance Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."}}}},"additionalProperties":false,"required":["d","usageDisclaimer","issuanceDisclaimer"]}]}},"additionalProperties":false,"required":["i","ri","s","d","e","r"]}

=== WebOfTrust/vLEI/samples/acdc/v1.1.0/legal-entity-vLEI-credential.json
{
  "v": "ACDC10JSON00011c_",
  "d": "EBdXt3gIXOf2BBWNHdSXCJnFJL5OuQPyM5K0neuniccM",
  "i": "did:keri:EmkPreYpZfFk66jpf3uFv7vklXKhzBrAqjsKAn2EDIPM",
  "ri": "did:keri:EymRy7xMwsxUelUauaXtMxTfPAMPAI6FkekwlOjkggt",
  "s": "E46jrVPTzlSkUPqGGeIZ8a8FWS7a6s4reAXRZOkogZ2A",
  "a": {
    "d": "EgveY4-9XgOcLxUderzwLIr9Bf7V_NHwY1lkFrn9y2PY",
    "i": "did:keri:EQzFVaMasUf4cZZBKA0pUbRc9T8yUXRFLyM1JDASYqAA",
    "dt": "2021-06-09T17:35:54.169967+00:00",
    "LEI": "254900OPPU84GM83MG36"
  },
  "e": {
    "d": "EIl3MORH3dCdoFOLe71iheqcywJcnjtJtQIYPvAu6DZA",
    "qvi": {
      "n": "Et2DOOu4ivLsjpv89vgv6auPntSLx4CvOhGUxMhxPS24",
      "s": "EBfdlu8R27Fbx-ehrqwImnK-8Cm79sqbAQ4MmvEAYqao"
    }
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."
    },
    "issuanceDisclaimer": {
      "l": "All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."
    }
  }
}
