=== WebOfTrust/vLEI/samples/oobis/.well-known/keri/oobi/EKA57bKBKxr_kN7iN5i7lMUxpMG-s19dRcmov1iDxz-E/index.json
{"$id":"EKA57bKBKxr_kN7iN5i7lMUxpMG-s19dRcmov1iDxz-E","$schema":"http://json-schema.org/draft-07/schema#","title":"OOR Authorization vLEI Credential","description":"A vLEI Authorization Credential issued by a Legal Entity to a QVI for the authorization of OOR credentials","type":"object","credentialType":"OORAuthorizationvLEICredential","version":"1.0.0","properties":{"v":{"description":"Version","type":"string"},"d":{"description":"Credential SAID","type":"string"},"u":{"description":"One time use nonce","type":"string"},"i":{"description":"LE Issuer AID","type":"string"},"ri":{"description":"Credential status registry","type":"string"},"s":{"description":"Schema SAID","type":"string"},"a":{"oneOf":[{"description":"Attributes block SAID","type":"string"},{"$id":"EPli-kppZ4gj8g4i3-FUx3ZG1H_UrMhXwzyP1E6uAot6","description":"Attributes block","type":"object","properties":{"d":{"description":"Attributes block SAID","type":"string"},"i":{"description":"QVI Issuee AID","type":"string"},"dt":{"description":"Issuance date time","format":"date-time","type":"string"},"AID":{"description":"AID of the intended recipient of the ECR credential","type":"string"},"LEI":{"description":"LEI of the requesting Legal Entity","type":"string","format":"ISO 17442"},"personLegalName":{"description":"Requested recipient name as provided during identity assurance","type":"string"},"officialRole":{"description":"Requested role description i.e. 'Head of Standards'","type":"string"}},"additionalProperties":false,"required":["i","dt","AID","LEI","personLegalName","officialRole"]}]},"e":{"oneOf":[{"description":"Edges block SAID","type":"string"},{"$id":"EB6E1GJvVen5NqkKb2TG5jqX66vYOL3md-xkXQqQBySX","description":"Edges block","type":"object","properties":{"d":{"description":"Edges block SAID","type":"string"},"le":{"description":"Chain to legal entity vLEI credential","type":"object","properties":{"n":{"description":"QVI Issuer credential SAID","type":"string"},"s":{"description":"SAID of required schema of the credential pointed to by this node","type":"string","const":"ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"}},"additionalProperties":false,"required":["n","s"]}},"additionalProperties":false,"required":["d","le"]}]},"r":{"oneOf":[{"description":"Rules block SAID","type":"string"},{"$id":"ECllqarpkZrSIWCb97XlMpEZZH3q4kc--FQ9mbkFMb_5","description":"Rules block","type":"object","properties":{"d":{"description":"Rules block SAID","type":"string"},"usageDisclaimer":{"description":"Usage Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."}}},"issuanceDisclaimer":{"description":"Issuance Disclaimer","type":"object","properties":{"l":{"description":"Associated legal language","type":"string","const":"All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."}}}},"additionalProperties":false,"required":["d","usageDisclaimer","issuanceDisclaimer"]}]}},"additionalProperties":false,"required":["i","ri","s","d","e","r"]}

=== WebOfTrust/vLEI/samples/acdc/v1.0.0/oor-authorization-vlei-credential.json
{
  "v": "ACDC10JSON0004e4_",
  "d": "EuF1gpodKbbqS0fqmUiOYf-MusuNvi0OmY8Js6SKSdfE",
  "i": "EKXPX7hWw8KK5Y_Mxs2TOuCrGdN45vPIZ78NofRlVBws",
  "ri": "EuqwB_iOD86eK0ynAhA6AYwWvPeBhvmbcmOD-9cCmiVU",
  "s": "EDpuiVPt4_sa1pShx6vOCnseru1edVPeNvRaQm6HrmMI",
  "a": {
    "d": "E9-86Jag34CrJpfNFz_-7E5HA0Dj0FvcYNoFVe7qwkiI",
    "dt": "2022-08-25T14:07:30.536257+00:00",
    "i": "EY4ldIBDZP4Tpnm3RX320BO0yz8Uz2nUSN-C409GnCJM",
    "AID": "Esf8b_AngI1d0KbOFjPGIfpVani0HTagWeaYTLs14PlE",
    "LEI": "6383001AJTYIGC8Y1X37",
    "personLegalName": "John Smith",
    "officialRole": "Chief Executive Officer"
  },
  "e": {
    "d": "EsOf5_YgX_64z4YuHNFWLUnIKcyvsVQOe_vJ_638X6gE",
    "le": {
      "n": "ESyLzoJC4L_1abXOEN4f6uNZCmhqyEHg2geBHFhJ8KDs",
      "s": "ENPXp1vQzRF6JwIuS-mp2U8Uf1MoADoP_GqQ62VsDZWY"
    }
  },
  "r": {
    "d": "EDIai3Wkd-Z_4cezz9nYEcCK3KNH5saLvZoS_84JL6NU",
    "usageDisclaimer": {
      "l": "Usage of a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, does not assert that the Legal Entity is trustworthy, honest, reputable in its business dealings, safe to do business with, or compliant with any laws or that an implied or expressly intended purpose will be fulfilled."
    },
    "issuanceDisclaimer": {
      "l": "All information in a valid, unexpired, and non-revoked vLEI Credential, as defined in the associated Ecosystem Governance Framework, is accurate as of the date the validation process was complete. The vLEI Credential has been issued to the legal entity or person named in the vLEI Credential as the subject; and the qualified vLEI Issuer exercised reasonable care to perform the validation process set forth in the vLEI Ecosystem Governance Framework."
    }
  }
}
